### ISSUE TITLE
GetAsync can't use with await

### ISSUE THREAD

**Issue by Leo-lay** [ziyasal/Httwrap#12]
HI,ziyasal:

 When I use Httwrap to request server 

`IHttwrapConfiguration configuration = new HttwrapConfiguration(ServerApiAddress.API_HOST);
			IHttwrapClient _httwrap = new HttwrapClient(configuration);
			`
**`var _response = await _httwrap.GetAsync(ServerApiAddress.VERSIFY_CODE);`**

here show follow error

 Error CS4033: The `await' operator can only be used when its containing method is marked with the `async' modifier (CS4033) (gp2_mobile)

**Comment by Leo-lay** [comment]
eh,not a issue,I wrong

**Comment by ziyasal** [comment]
@Leo-lay nope (:
