### ISSUE TITLE
Using Httwrap with list of same objects

### ISSUE THREAD

**Issue by PhotoSonic** [ziyasal/Httwrap#19]
Hi ziyasal!

I have a problem/question.. If in my controller i have Http Get method ..

        [HttpGet("/api/Visit/AccessPoints/")]
        public IEnumerable<Visit> GetByAccessPoints([FromQuery]List<Guid> id)
        {
            return visitService.GetByAccessPoints(id);
        }

Endpoint is something like..
https://localhost:44388/api/Visit/AccessPoints?id=98fa2138-e2af-4dea-ad63-dfec82df1131&id=39d8f189-ceea-4789-af21-3700989d906c&id=f4e9930c-6f67-40e6-90b4-b507581047d8

So, as you can see I have a list of ids/guids... How I am using httwrap?
If I use
`await httpWrapper.GetAsync<IEnumerable<Visit>>(url, ids);`

queryStringBuilder doesn't build right url

Thanx in advance

**Comment by bugthesystem** [comment]
Hi @PhotoSonic, the quick way to achieve this would be to build a URL with these ids and then call `.GetAsync` with the URL you have built. Query builder supports only key-value types (incl. objects). Hope this helps 🙂

Example:
```c#
var ids = new int[] {1,2,3,4};
var str = string.Join("&", ids.Select(id => string.Format("id={0}", id)));
Console.WriteLine(str);

// id=1&id=2&id=3&id=4
```
